import Head from "next/head";
import type { GetStaticProps } from "next";
import { createClient } from "contentful";
import GalleryCard from "../components/Card";
import Footer from "../components/Footer";
import { StyledHome } from "../components/Styled/Home.style";
import { GlobalStyles } from "../components/Styled/Global";

export default function Home({ galleries }: any) {
  return (
    <>
      <Head>
        <title>Milly Tillson | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />

      <StyledHome>
        {galleries.map((gallery: any) => {
          return (
            <div>
              <GalleryCard
                gallery={gallery}
                image={gallery.fields.images[0]}
                key={gallery.sys.id}
              />
            </div>
          );
        })}
      </StyledHome>

      <Footer />
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: "gallery" });

  return {
    props: {
      galleries: res.items,
    },
  };
};
