import Head from "next/head";
import type { GetStaticProps } from "next";
import Image from "next/image";
import css from "../styles/Home.module.scss";
import { createClient } from "contentful";
import GalleryCard from "../components/GalleryCard";

export default function Home({ galleries }: any) {
  // const galleryCards = ({ galleries.map((gallery: any) => (
  //   <GalleryCard
  //     gallery={gallery}
  //     image={gallery.fields.images[0]}
  //     key={gallery.sys.id}
  //   />
  // })

  return (
    <>
      <Head>
        <title>Milly Tillson | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={css.homepage}>
        <div className={css.cardContainer}>
          {galleries.length > 0 && (
            <div className={css.cardContainer__card0}>
              <GalleryCard
                gallery={galleries[0]}
                image={galleries[0].fields.images[0]}
                key={galleries[0].sys.id}
              />
            </div>
          )}
          {galleries.length > 1 && (
            <div className={css.cardContainer__card1}>
              <GalleryCard
                gallery={galleries[1]}
                image={galleries[1].fields.images[0]}
                key={galleries[1].sys.id}
              />
            </div>
          )}
        </div>
      </section>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: "gallery" });

  return {
    props: {
      galleries: res.items,
    },
  };
};
